using TListPlugin; 
[System.Serializable]
public class GetDataSO_SD_KeyStorageBoolVariable : Abs_Get_SO_IdentifierAndData<SO_Data_SD_KeyStorageBoolVariable,IdentifierAndData_SD_KeyStorageBoolVariable, IndifNameSO_SD_KeyStorageBoolVariable, string, SD_KeyStorageBoolVariable>
{

}
