using TListPlugin; 
[System.Serializable]
public class GetDataSO_SD_KeyStorageStringVariable : Abs_Get_SO_IdentifierAndData<SO_Data_SD_KeyStorageStringVariable,IdentifierAndData_SD_KeyStorageStringVariable, IndifNameSO_SD_KeyStorageStringVariable, string, SD_KeyStorageStringVariable>
{

}
